#!/usr/bin/env python3
"""Generates OmarchyThemes.kt from an Omarchy checkout.

Every theme's colors.toml is resolved with Omarchy's own resolver
(bin/omarchy-theme-color --all), so the bundled palettes carry exactly the
values Omarchy bakes into its terminal configs. Conductore's generator pins
the same Omarchy commit, so both apps ship identical palettes.

Usage: tools/generate_omarchy_themes.py <omarchy-checkout> [commit]
Omarchy is MIT licensed (c) David Heinemeier Hansson.
"""
import os
import subprocess
import sys

DEFAULT_COMMIT = 'c3e67f5d405047765d47a9336a3df115a7beecfb'

# (colors.toml key, OmarchyTheme constructor field)
FIELDS = [
    ('accent', 'accent'),
    ('background', 'background'),
    ('foreground', 'foreground'),
    ('selection', 'selection'),
    ('muted', 'muted'),
    ('dark_background', 'darkBackground'),
    ('lighter_background', 'lighterBackground'),
    ('red', 'red'),
    ('green', 'green'),
    ('yellow', 'yellow'),
    ('blue', 'blue'),
    ('magenta', 'magenta'),
    ('cyan', 'cyan'),
    ('orange', 'orange'),
]


def label(slug):
    return ' '.join(part.capitalize() for part in slug.split('-'))


def color(value):
    value = value.strip().lstrip('#')
    if len(value) != 6:
        raise SystemExit(f'unexpected colour {value!r}')
    return f'0xFF{value.upper()}.toInt()'


def main():
    root = sys.argv[1]
    commit = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_COMMIT
    themes_dir = os.path.join(root, 'themes')
    resolver = os.path.join(root, 'bin', 'omarchy-theme-color')
    out = [
        '// GENERATED by tools/generate_omarchy_themes.py. Do not edit by hand.',
        '//',
        '// Source: https://github.com/basecamp/omarchy themes/*/colors.toml at',
        f'// commit {commit}, resolved with bin/omarchy-theme-color --all.',
        '// Omarchy is MIT licensed, Copyright (c) David Heinemeier Hansson.',
        '',
        'package com.outsmartis.yoke.theme',
        '',
        '/** Every theme Omarchy ships, in directory-name order. */',
        'val OMARCHY_THEMES: List<OmarchyTheme> = listOf(',
    ]
    for slug in sorted(os.listdir(themes_dir)):
        colors_file = os.path.join(themes_dir, slug, 'colors.toml')
        if not os.path.isfile(colors_file):
            continue
        resolved = subprocess.run(
            ['bash', resolver, '--file', colors_file, '--all'],
            check=True, capture_output=True, text=True,
        ).stdout
        values = dict(line.split('\t', 1) for line in resolved.splitlines() if '\t' in line)
        out.append('    OmarchyTheme(')
        out.append(f'        id = "{slug}",')
        out.append(f'        name = "{label(slug)}",')
        out.append(f"        dark = {'true' if values['mode'] == 'dark' else 'false'},")
        for key, field in FIELDS:
            out.append(f'        {field} = {color(values[key])},')
        out.append('    ),')
    out.append(')')
    out.append('')
    target = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'app', 'src', 'main',
                          'java', 'com', 'outsmartis', 'yoke', 'theme', 'OmarchyThemes.kt')
    with open(target, 'w') as handle:
        handle.write('\n'.join(out))


if __name__ == '__main__':
    main()
